In [2]:
import numpy as np

## Task number 1
### Create a one-dimensional array (vector) with the first 10 positive integers and print its value.

In [14]:
my_array = np.arange(0, 11, dtype=int)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Task number 2
### Create a two-dimensional array (matrix) of size 3x3, fill it with zeros and print its value.

In [7]:
my_matrix = np.zeros((3, 3), dtype=int)
print(my_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Task nubmer 3
### Create an array of size 5x5, fill it with random integers in the range from 1 to 10 and print its value.

In [11]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 2  9  2  4  6]
 [ 6  1  8  6  3]
 [ 9  6  9  6  2]
 [ 4  3  7 10  6]
 [ 6  5 10  9  4]]


## Task number 4
### Create an array of size 4x4, fill it with random real numbers in the range from 0 to 1 and print its value.

In [42]:
random_matrix = np.random.rand(4, 4)

print(random_matrix)

[[0.78404905 0.39272703 0.38517782 0.36010531]
 [0.73201634 0.29288652 0.87143196 0.55463789]
 [0.84709936 0.74151566 0.92168619 0.21088886]
 [0.09649009 0.73650887 0.83782114 0.25877783]]


## Task number 5
### Create two one-dimensional arrays of size 5, fill them with random integers in the range from 1 to 10, and perform addition, subtraction, and multiplication operations on them.

In [23]:
random_ar_1 = np.random.randint(1, 11, size=(5))
random_ar_2 = np.random.randint(1, 11, size=(5))

print(random_ar_1 + random_ar_2)
print(random_ar_1 - random_ar_2)
print(random_ar_1 * random_ar_2)

[ 7 11  7 10 17]
[-3 -7  5 -2  1]
[10 18  6 24 72]


## Task number 6
### Create two vectors of size 7, fill them with arbitrary numbers and find their scalar product.

In [29]:
random_ar_1 = np.random.randint(1, 21, size=(7))
random_ar_2 = np.random.randint(1, 21, size=(7))

print(np.dot(random_ar_1, random_ar_2))

627


## Task number 7
### Create two matrices of size 2x2 and 2x3, fill them with random integers in the range from 1 to 10, and multiply them.

In [30]:
random_mat_1 = np.random.randint(1, 11, size=(2,2))
random_mat_2 = np.random.randint(1, 11, size=(2,3))

print(np.dot(random_mat_1, random_mat_2))

[[ 26  39  41]
 [128 126 113]]


## Task number 8
### Create a 3x3 matrix, fill it with random integers in the range from 1 to 10, and find its inverse.

In [31]:
random_mat = np.random.randint(1, 11, size=(3,3))

print(np.linalg.inv(random_mat))

[[-0.17647059  0.11764706  0.11764706]
 [-0.05042017 -0.1092437   0.46218487]
 [ 0.18487395  0.06722689 -0.36134454]]


## Task number 9
### Create a 4x4 matrix, fill it with random real numbers in the range from 0 to 1, and transpose it.

In [40]:
random_mat = np.random.rand(4, 4)

print(random_mat.T)

[[0.44642813 0.88117185 0.34029765 0.19903356]
 [0.5183789  0.38057021 0.05171318 0.01613755]
 [0.26854506 0.4254735  0.79078525 0.4666817 ]
 [0.1506999  0.19507184 0.35485438 0.12147467]]


## Task number 10
### Create a matrix of size 3x4 and a vector of size 4, fill them with random integers in the range from 1 to 10, and multiply the matrix by the vector.

In [8]:
random_mat = np.random.randint(1, 11, size=(3,4))
random_ar = np.random.randint(1, 11, size=(4))

print(np.dot(random_mat, random_ar))

[126 136  94]


## Task number 11
### Create a matrix of size 2x3 and a vector of size 3, fill them with random real numbers in the range from 0 to 1, and multiply the matrix by the vector.

In [39]:
random_mat = np.random.rand(2, 3)
random_ar = np.random.rand(3)

print(np.dot(random_mat, random_ar))

[0.49585091 0.5138499 ]


## Task number 12
### Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10, and perform their elementwise multiplication.

In [19]:
random_mat_1 = np.random.randint(1, 11, size=(2,2))
random_mat_2 = np.random.randint(1, 11, size=(2,2))

print(random_mat_1 * random_mat_2)

[[ 6 48]
 [50 14]]


## Task number 13
### Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10 and find their product.

In [22]:
random_mat_1 = np.random.randint(1, 11, size=(2,2))
random_mat_2 = np.random.randint(1, 11, size=(2,2))

print(np.dot(random_mat_1, random_mat_2))

[[ 82  92]
 [101 113]]


## Task number 14
### Create a 5x5 matrix, fill it with random integers in the range from 1 to 100, and find the sum of the matrix elements.

In [35]:
random_big_mat = np.random.randint(1, 101, size=(5,5))

print(np.sum(random_big_mat))

1310


## Task number 15
### Create two matrices of size 4x4, fill them with random integers in the range from 1 to 10 and find their difference.

In [36]:
random_mat_1 = np.random.randint(1, 11, size=(4,4))
random_mat_2 = np.random.randint(1, 11, size=(4,4))

print(random_mat_1 - random_mat_2)

[[ 1 -7  0 -3]
 [ 0  0  2  0]
 [ 1  1  6  7]
 [-2 -2 -6 -3]]


## Task number 16
### Create a matrix of size 3x3, fill it with random real numbers in the range from 0 to 1, and find the column vector containing the sum of the elements of each row of the matrix.

In [44]:
random_mat = np.random.rand(3, 3)
vector = np.sum(random_mat, axis=1)
column_vector = vector.reshape(-1, 1)

print(column_vector)

[[1.73220855]
 [1.15616324]
 [1.88692407]]


## Task number 17
### Create a 3x4 matrix with any integers and create a matrix with the squares of these numbers.

In [45]:
mat_1 = np.random.randint(1, 11, size=(3,4))

print(np.square(mat_1))

[[81  9  4 49]
 [ 4 49 81 49]
 [49  9 49 16]]


## Task number 18
### Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [50]:
random_ar_1 = np.random.randint(1, 51, size=4)

print(random_ar_1, np.sqrt(random_ar_1))

[ 7 11 29 46] [2.64575131 3.31662479 5.38516481 6.78232998]
